
// This file has been generated by the GUI designer. Do not modify.
namespace MyTestCreator
{
	public partial class OneStringAskDlg
	{
		private global::Gtk.Label label1;
		
		private global::Gtk.Entry txtValue;
		
		private global::Gtk.CheckButton chkbtnCorrectAnswer;
		
		private global::Gtk.Button buttonCancel;
		
		private global::Gtk.Button buttonOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MyTestCreator.OneStringAskDlg
			this.Name = "MyTestCreator.OneStringAskDlg";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Resizable = false;
			this.AllowGrow = false;
			// Internal child MyTestCreator.OneStringAskDlg.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("%s");
			this.label1.Justify = ((global::Gtk.Justification)(2));
			w1.Add (this.label1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(w1 [this.label1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.txtValue = new global::Gtk.Entry ();
			this.txtValue.CanFocus = true;
			this.txtValue.Name = "txtValue";
			this.txtValue.IsEditable = true;
			this.txtValue.InvisibleChar = '●';
			w1.Add (this.txtValue);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(w1 [this.txtValue]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.chkbtnCorrectAnswer = new global::Gtk.CheckButton ();
			this.chkbtnCorrectAnswer.CanFocus = true;
			this.chkbtnCorrectAnswer.Name = "chkbtnCorrectAnswer";
			this.chkbtnCorrectAnswer.Label = global::Mono.Unix.Catalog.GetString ("%s");
			this.chkbtnCorrectAnswer.DrawIndicator = true;
			this.chkbtnCorrectAnswer.UseUnderline = true;
			w1.Add (this.chkbtnCorrectAnswer);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(w1 [this.chkbtnCorrectAnswer]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			// Internal child MyTestCreator.OneStringAskDlg.ActionArea
			global::Gtk.HButtonBox w5 = this.ActionArea;
			w5.Name = "dialog1_ActionArea";
			w5.Homogeneous = true;
			w5.Spacing = 10;
			w5.BorderWidth = ((uint)(5));
			w5.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(2));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w6 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w5 [this.buttonCancel]));
			w6.Expand = false;
			w6.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w7 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w5 [this.buttonOk]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 121;
			this.Show ();
		}
	}
}
