
// This file has been generated by the GUI designer. Do not modify.
namespace MyTestCreator
{
	public partial class OneStringValueAskDlg
	{
		private global::Gtk.Label lblAskText;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.Label lblUpperText;
		
		private global::Gtk.Entry txtText;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Label lblLowerText;
		
		private global::Gtk.SpinButton spinbtnValue;
		
		private global::Gtk.Button buttonCancel;
		
		private global::Gtk.Button buttonOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MyTestCreator.OneStringValueAskDlg
			this.Name = "MyTestCreator.OneStringValueAskDlg";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Resizable = false;
			this.AllowGrow = false;
			// Internal child MyTestCreator.OneStringValueAskDlg.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.lblAskText = new global::Gtk.Label ();
			this.lblAskText.Name = "lblAskText";
			this.lblAskText.LabelProp = global::Mono.Unix.Catalog.GetString ("AskText");
			w1.Add (this.lblAskText);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(w1 [this.lblAskText]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.lblUpperText = new global::Gtk.Label ();
			this.lblUpperText.Name = "lblUpperText";
			this.lblUpperText.LabelProp = global::Mono.Unix.Catalog.GetString ("Upper Text");
			this.hbox2.Add (this.lblUpperText);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.lblUpperText]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.txtText = new global::Gtk.Entry ();
			this.txtText.CanFocus = true;
			this.txtText.Name = "txtText";
			this.txtText.IsEditable = true;
			this.txtText.InvisibleChar = '●';
			this.hbox2.Add (this.txtText);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.txtText]));
			w4.Position = 1;
			w1.Add (this.hbox2);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(w1 [this.hbox2]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.lblLowerText = new global::Gtk.Label ();
			this.lblLowerText.Name = "lblLowerText";
			this.lblLowerText.LabelProp = global::Mono.Unix.Catalog.GetString ("Lower Text");
			this.hbox1.Add (this.lblLowerText);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.lblLowerText]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.spinbtnValue = new global::Gtk.SpinButton (0, 1000, 1);
			this.spinbtnValue.CanFocus = true;
			this.spinbtnValue.Name = "spinbtnValue";
			this.spinbtnValue.Adjustment.PageIncrement = 10;
			this.spinbtnValue.ClimbRate = 1;
			this.spinbtnValue.Numeric = true;
			this.hbox1.Add (this.spinbtnValue);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.spinbtnValue]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			w1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(w1 [this.hbox1]));
			w8.Position = 2;
			w8.Expand = false;
			w8.Fill = false;
			// Internal child MyTestCreator.OneStringValueAskDlg.ActionArea
			global::Gtk.HButtonBox w9 = this.ActionArea;
			w9.Name = "dialog1_ActionArea";
			w9.Spacing = 10;
			w9.BorderWidth = ((uint)(5));
			w9.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(2));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w10 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w9 [this.buttonCancel]));
			w10.Expand = false;
			w10.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w11 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w9 [this.buttonOk]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 427;
			this.DefaultHeight = 130;
			this.Show ();
		}
	}
}
