
// This file has been generated by the GUI designer. Do not modify.
namespace MyTest
{
	public partial class ResultsWindow
	{
		private global::Gtk.VBox vbox3;
		
		private global::Gtk.Label lblTestName;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.NodeView resultsView;
		
		private global::Gtk.HButtonBox hbuttonbox6;
		
		private global::Gtk.Button btnNewTest;
		
		private global::Gtk.Button btnQuit;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MyTest.ResultsWindow
			this.Name = "MyTest.ResultsWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("ResultsWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			// Container child MyTest.ResultsWindow.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.lblTestName = new global::Gtk.Label ();
			this.lblTestName.Name = "lblTestName";
			this.lblTestName.LabelProp = global::Mono.Unix.Catalog.GetString ("Test Name");
			this.vbox3.Add (this.lblTestName);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.lblTestName]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.resultsView = new global::Gtk.NodeView ();
			this.resultsView.CanFocus = true;
			this.resultsView.Name = "resultsView";
			this.GtkScrolledWindow.Add (this.resultsView);
			this.vbox3.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.GtkScrolledWindow]));
			w3.Position = 1;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbuttonbox6 = new global::Gtk.HButtonBox ();
			this.hbuttonbox6.Name = "hbuttonbox6";
			this.hbuttonbox6.Homogeneous = true;
			// Container child hbuttonbox6.Gtk.ButtonBox+ButtonBoxChild
			this.btnNewTest = new global::Gtk.Button ();
			this.btnNewTest.CanFocus = true;
			this.btnNewTest.Name = "btnNewTest";
			this.btnNewTest.UseUnderline = true;
			this.btnNewTest.Label = global::Mono.Unix.Catalog.GetString ("Новый тест (New Test)");
			global::Gtk.Image w4 = new global::Gtk.Image ();
			w4.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-new", global::Gtk.IconSize.LargeToolbar);
			this.btnNewTest.Image = w4;
			this.hbuttonbox6.Add (this.btnNewTest);
			global::Gtk.ButtonBox.ButtonBoxChild w5 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox6 [this.btnNewTest]));
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbuttonbox6.Gtk.ButtonBox+ButtonBoxChild
			this.btnQuit = new global::Gtk.Button ();
			this.btnQuit.CanFocus = true;
			this.btnQuit.Name = "btnQuit";
			this.btnQuit.UseUnderline = true;
			this.btnQuit.Label = global::Mono.Unix.Catalog.GetString ("Выход (Quit)");
			global::Gtk.Image w6 = new global::Gtk.Image ();
			w6.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-quit", global::Gtk.IconSize.LargeToolbar);
			this.btnQuit.Image = w6;
			this.hbuttonbox6.Add (this.btnQuit);
			global::Gtk.ButtonBox.ButtonBoxChild w7 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox6 [this.btnQuit]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			this.vbox3.Add (this.hbuttonbox6);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbuttonbox6]));
			w8.Position = 2;
			w8.Expand = false;
			w8.Fill = false;
			this.Add (this.vbox3);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 719;
			this.DefaultHeight = 468;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.SizeAllocated += new global::Gtk.SizeAllocatedHandler (this.MakeFullscreen);
			this.btnNewTest.Clicked += new global::System.EventHandler (this.NewTest);
			this.btnQuit.Clicked += new global::System.EventHandler (this.BtnQuitClick);
		}
	}
}
